version: '3'
services:
  db:
    image: mysql:8.3
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  app:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=testdb
      - DB_PORT=3306
    links:
      - db
    command: >
      sh -c "npm install && npm run for-docker-database && npm run dev"
      
volumes:
  db_data: {}